ARG VARIANT=7
FROM mcr.microsoft.com/vscode/devcontainers/powershell:${VARIANT}

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
